-- Migration 004: Game Plans Table
-- Purpose: Persist Master Game Plans generated by GamePlanAgent
-- Date: 2026-01-27

-- Create game_plans table
CREATE TABLE IF NOT EXISTS game_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL,
    plan_data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Metadata for quick queries
    narrative_brand TEXT,
    current_ivy_score FLOAT,
    target_ivy_score FLOAT,
    activity_count INT DEFAULT 10,
    
    -- Constraints
    CONSTRAINT fk_student
        FOREIGN KEY (student_id)
        REFERENCES students(id)
        ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_game_plans_student 
    ON game_plans(student_id);

CREATE INDEX IF NOT EXISTS idx_game_plans_created 
    ON game_plans(created_at DESC);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_game_plan_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER trigger_update_game_plan_timestamp
    BEFORE UPDATE ON game_plans
    FOR EACH ROW
    EXECUTE FUNCTION update_game_plan_timestamp();

-- Comments for documentation
COMMENT ON TABLE game_plans IS 'Stores Master Game Plans generated by GamePlanAgent (v7.1)';
COMMENT ON COLUMN game_plans.plan_data IS 'Complete MasterGamePlan JSON (activities, school_strategies, phases, identity_seeds)';
COMMENT ON COLUMN game_plans.narrative_brand IS 'Student brand statement for quick reference';
